### ISSUE TITLE
Possible synergy with FCOP

### ISSUE THREAD

**Issue by jdegoes** [TheTumboliaSociety/discussion#4]
I am one of the organizers for LambdaConf, which is one of the few conferences that has successfully taken a stand for enforcing a clear separation between personal and professional spheres.

Part of the fallout of the LambdaConf controversy is a new "non-political" code of conduct, whose adoptance by an organization essentially prevents them from banning or uninviting people based on unpopular political, religious, or philosophical views, or attitudes.

This code of conduct is called _Fantasyland Institute of Learning - Code of Professionalism_, or FCOP for short. See [here](http://degoes.net/articles/introducing-fcop) for an introduction.

I wonder if the Tumbolia Society shares similar enough goals to collaborate?

**Comment by leurfete** [comment]
Thanks for pointing this out! Yes. I think we're 100% on the same page. I'll add info about this to the webpage, etc... at a minimum.

**Comment by leurfete** [comment]
@jdegoes I've noticed that fantasyland.institute is empty at the moment. Is setting this up something I could help with? I can do something cleaner than what I've janked together for TTS. Also, should we consider setting up an irc channel for quicker communication?

**Comment by jdegoes** [comment]
Yes, we could use some help with that. We've got a site layout and some graphics, and we *had* an intern, but that didn't end up working out, so the site is kind of in limbo. 

If you'd like to help out, we were going to do a full scholarship to any LC event (if you like or are interested in functional programming), or we can just do straight up compensation too (albeit nothing too extravagant as we're a non-profit :).

Shoot me an email — john / fantasyland / institute — and we can chat further and get you onto the Slack we use for events (or possibly setup an IRC channel).

Thanks, by the way, for blogging about FCOP. Really like what you're trying to do with TS and greatly appreciate the support.

**Comment by leurfete** [comment]
@jdegoes Sent, just let me know if I need to try again.
